### ISSUE TITLE
Symbols in black

### ISSUE THREAD

**Issue by lixianguser** [dracula/visual-studio#19] opened 2021-10-01 09:47 UTC
Why are the symbols in black so that they cannot be seen clearly, can they be modified?

By the way, it's visual studio for Mac.

<img width="561" alt="截屏2021-10-01 下午5 42 19" src="https://user-images.githubusercontent.com/36319693/135599705-9b936d96-a3c5-4b0d-b7dd-5b1e54db14e4.png">

**Comment by gbougeniere** [comment] 2021-12-20 15:30
Probably a duplicate of #16. You'll find a workaround in the linked issue.

**Closed** 2022-05-10 04:06 UTC
